# Limits for loops
set_directive_loop_tripcount -min 19 -max   19 "dev_hls/RESET_REGISTERS"
set_directive_loop_tripcount -min  1 -max 4096 -avg 64 "dev_hls/COPY_LOOP"
set_directive_loop_tripcount -min  1 -max 4096 -avg 64 "dev_hls/ARITHMETIC_LOOP"
set_directive_loop_tripcount -min  1 -max 4096 -avg 64 "dev_hls/COUNT_LOOP"
set_directive_loop_tripcount -min  1 -max   64 -avg  8 "dev_hls/MMUL_SRC1_ROWS"
set_directive_loop_tripcount -min  1 -max   64 -avg  8 "dev_hls/MMUL_SRC2_COLS"
set_directive_loop_tripcount -min  1 -max   64 -avg  8 "dev_hls/MMUL_SRC1_COLS"
set_directive_loop_tripcount -min  1 -max 4096 -avg 64 "dev_hls/MSUM_LOOP"
set_directive_loop_tripcount -min  1 -max 4096 -avg 64 "dev_hls/EQUAL_LOOP"
set_directive_loop_tripcount -min  1 -max   64 -avg  8 "dev_hls/TRANS_ROWS"
set_directive_loop_tripcount -min  1 -max   64 -avg  8 "dev_hls/TRANS_COLS"
set_directive_loop_tripcount -min  1 -max 4096 -avg 64 "dev_hls/FILL_LOOP"
set_directive_loop_tripcount -min  1 -max   64 -avg  8 "dev_hls/IDENT_ROWS"
set_directive_loop_tripcount -min  1 -max   64 -avg  8 "dev_hls/IDENT_COLS"
